## Load the docker image to be used my the runner
image: continuumio/miniconda3:latest

## All stages could be customized. The following are just examples
stages:
  - test_homolog
  - test_master
  - deploy_snap
  - deploy

test_homolog:
  stage: test_homolog
  script:
    ## Install gcc
    - apt-get update
    - apt-get install -y gcc g++

    ## Install mongodb needed for integration tests
    - apt-get install -y gnupg curl
    - curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | \
      sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
      --dearmor
    - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
    - apt-get update
    - sudo apt-get install -y mongodb-org

    ## Create Conda environment
    - conda create -n model python=3.9
    - source activate model

    - pip install --upgrade pip coverage
    ## Install requirements
    - pip install --extra-index-url https://$GS_PYPI_USER:$GS_PYPI_PWD@nexus.giantsteps.me/repository/gs_pypi_snapshot/simple/ .[tests]

    ## Only run unittests - Integration tests are run apart
    - coverage run -m pytest tests/ -v
    - coverage report
  coverage: '/TOTAL[\s\d]+\s(\d{1,3}%)/'

test_master:
  stage: test_master
  only:
    - master
  script:
    ## Install gcc
    - apt-get update
    - apt-get install -y gcc g++

    ## Install libssl needed for MongoDB
    - wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  
    ## Install mongodb needed for integration tests
    - apt-get install -y gnupg curl
    - curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | \
      sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
      --dearmor
    - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
    - apt-get update
    - sudo apt-get install -y mongodb-org

    ## Create Conda environment
    - conda create -n model python=3.9
    - source activate model

    - pip install --upgrade pip coverage
    ## Install requirements
    - pip install --extra-index-url https://$GS_PYPI_USER:$GS_PYPI_PWD@nexus.giantsteps.me/repository/gs_pypi/simple/ .[tests]
    ## Only run unittests - Integration tests are run apart
    - coverage run -m pytest tests/unit -v
    - coverage report
  coverage: '/TOTAL[\s\d]+\s(\d{1,3}%)/'

deploy_snap:
  stage: deploy_snap
  only:
    - homolog
  script:
    - conda create -n deployer python=3.9
    - source activate deployer
    - pip install --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - twine upload -u $GS_PYPI_USER -p $GS_PYPI_PWD --repository-url https://nexus.giantsteps.me/repository/gs_pypi_snapshot/ dist/*

deploy:
  stage: deploy
  only:
    - master
  script:
    - conda create -n deployer python=3.9
    - source activate deployer
    - pip install --upgrade setuptools wheel twine
    - python setup.py sdist bdist_wheel
    - twine upload -u $GS_PYPI_USER -p $GS_PYPI_PWD --repository-url https://nexus.giantsteps.me/repository/gs_pypi/ dist/*
