defaults: &defaults
    parallelism: 1
    shell: /bin/bash --login
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run:
        name: Version checks
        command: |
            VERSION=`fgrep '###' CHANGES.md  | awk '{print $2}' | head -1`
            echo picked up VERSION=$VERSION from CHANGES.md
            grep -q $VERSION CHANGES.md || (echo "ERROR: Version number not found in CHANGES.md: $VERSION"; exit 1)
    - run:
        name: Output useful stuff
        command: |
          echo $VERSION > "$CIRCLE_ARTIFACTS/version.txt"
    - run:
        name: Install MongoDB 4.4
        command: |
            # run "cat /etc/os-release" to view information about the OS
            # good article on how to install mongo, https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
            cat /etc/os-release
            set -x
            # ------ (2022-10-28) install libssl1.1 since mongo doesn't support Ubuntu 22.04 which has libssl v3 
            echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
            sudo apt-get update
            sudo apt-get install libssl1.1
            # -------
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            sudo apt-get install gnupg
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            sudo apt-get update
            sudo ln -Tf /bin/true /usr/bin/systemctl
            sudo apt-get install -y mongodb-org=4.4.18 mongodb-org-server=4.4.18 mongodb-org-shell=4.4.18 mongodb-org-mongos=4.4.18 mongodb-org-tools=4.4.18
            sudo rm /usr/bin/systemctl

            sudo rm /etc/apt/sources.list.d/focal-security.list
    - run:
       name: Create and activate virtualenv
       command: |
         virtualenv ci
         . ci/bin/activate
         python setup.py develop
         pip install --upgrade pip
         pip install pytest-server-fixtures[mongodb]
         echo y | pip uninstall tzlocal # because circleci will install >5.0b
         pip install tzlocal==4.2 # works for python 3.6 and 3.8
         pip freeze
         python --version
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/ci
    # Test
    - run:
        name: Run all tests
        command: |
         set -x
         . ci/bin/activate
         ls -la /bin | grep mongo
         mongod --version
         mkdir test-results
         #py.test -svvvvv --junitxml=test-results/junit.xml
         python setup.py test --pytest-args=-v
    - store_test_results:
        path: test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: test-results
    - persist_to_workspace:
        root: /tmp/circleci-artifacts
        paths:
          - ./*/version.txt
          - ./*/changes.md
          - ./*/dist/*
version: 2
jobs:
  build_3_6:
    environment:
      PYTHON_VERSION: "3_6"
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_6
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results/3_6
      VERSION: $VERSION
      IMAGE_NAME: mangroup/arctic
    working_directory: ~/arctic_3_6
    docker:
    - image: cimg/python:3.6-node
    <<: *defaults
    #resource_class: large
  build_3_7:
    environment:
      PYTHON_VERSION: "3_7"
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_7
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results/3_7
      VERSION: $VERSION
      IMAGE_NAME: mangroup/arctic
    working_directory: ~/arctic_3_7
    docker:
    - image: cimg/python:3.7-node
    <<: *defaults
    #resource_class: large
  build_3_8:
    environment:
      PYTHON_VERSION: "3_8"
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts/3_8
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results/3_8
      VERSION: $VERSION
      IMAGE_NAME: mangroup/arctic
    working_directory: ~/arctic_3_8
    docker:
    - image: cimg/python:3.8-node
    <<: *defaults
    #resource_class: large
  publish-github-release:
   docker:
     - image: cibuilds/github:0.13
   steps:
     - attach_workspace:
         at: /tmp/circleci-artifacts
     - run:
         name: "Publish release on GitHub"
         command: |
           VERSION=$(cat /tmp/circleci-artifacts/3_6/version.txt)
           CHANGES=$(cat /tmp/circleci-artifacts/3_6/changes.md)
           ghr -t ${GITHUB_TOKEN} \
               -u ${CIRCLE_PROJECT_USERNAME} \
               -r ${CIRCLE_PROJECT_REPONAME} \
               -c ${CIRCLE_SHA1} \
               -n ${VERSION} \
               -b "${CHANGES}" \
               -soft \
               ${VERSION} /tmp/circleci-artifacts/3_6/dist
workflows:
  version: 2
  build_all:
    jobs:
      - build_3_6
      - build_3_7
      - build_3_8

      # do not publish
      #- publish-github-release:
      #    requires:
      #      - build_3_6
      #      - build_3_7
      #    filters:
      #      branches:
      #        only:
      #          - master
